dandi/dandi-schema

- .github/workflows/publish-schemata.yml
See https://github.com/dandi/dandischema/issues/2 for discussion on how to
be done etc
> RF(TEMP): disable publishing new versions of schemata

- dandischema/models.py
- dandischema/tests/data/metadata/asset_001.json
- dandischema/tests/test_metadata.py
- dandischema/tests/test_models.py
The check for digest assumed an md5sum. however, the digest has an extra component and are of the form: `<md5sum>-<chunks>`
> fix: dandi-etag carries extra component beyond md5

- .github/workflows/release.yml
> Use DANDI_GITHUB_TOKEN to check out dandi/schema when releasing

- dandischema/metadata.py
- dandischema/tests/test_metadata.py
- dandischema/tests/test_utils.py
- dandischema/utils.py
I just ran through all the dandiset metadata and this code wasn't taking badly formed metadata into account.
> fix: update migration code to account for missing fields

- dandischema/models.py
Development/test environments use an object store that is generally
served at `localhost:9000`. URLs that point to objects in this store
obviously have the form `http://localhost:9000/{...}`. The pydantic
field `HttpUrl` requires a TLD, which excludes `localhost`. Instead, we
should use `AnyHttpUrl` which allows `localhost`.
> Allow location fields to have localhost URLs

- dandischema/consts.py
- dandischema/metadata.py
Allow migrating from versions greater 0.3.1
> fix: allow migration for versions greater than 0.3.2

- dandischema/datacite.py
- dandischema/models.py
- dandischema/tests/test_datacite.py
- dandischema/tests/test_models.py
1. updates datacite constructor to ensure
- contributorType
- support validation against jsonschema from datacite (this may not be authoritative and should be used with care)
2. ensure that round tripping of schemaKey creates the same object or raises a validation error
closes https://github.com/dandi/dandi-api/issues/347
> Fix: Make the library more robust for publishing

- .pre-commit-config.yaml
> Add flake8 to .pre-commit-config.taml

- dandischema/consts.py
- dandischema/models.py
- dandischema/tests/data/metadata/meta_000004.json
- dandischema/tests/data/metadata/meta_000004old.json
- dandischema/tests/data/metadata/meta_000008.json
- dandischema/tests/test_datacite.py
- dandischema/tests/test_models.py
This improves a bunch of validation specs for publish.  However, the current implementation is completely predicated on production servers and prefixes. 
Calling this a draft for now while we think about how to get info about the domain in which the schema is running. technically for most users everything should validate against the production sites. but devs may need other things.
> enh: update models to do more validation checks

- .github/workflows/release.yml
> release.yml: Use DANDI_GITHUB_TOKEN to push to repo

- dandischema/metadata.py
- dandischema/tests/test_metadata.py
adding a mechanism to allow checking that a metadata blob for dandiset or asset has proper values given the schema, but may have missing fields. these metadata objects should be ok for posting but not for publishing.
@dchiquito and @jwodder - would this be useful?
> enh: allow checking to see data are matched but allow for missing fields

- .github/workflows/test-dandi-cli.yml
> Add workflow for testing dandischema against latest release of dandi-cli

- dandischema/tests/test_datacite.py
an RRID can be associated with different versions, therefore cannot be used as the id of an object. this fixes this in a test.
> fix: change id to indentifier for software

- dandischema/consts.py
- dandischema/models.py
- dandischema/tests/data/metadata/asset_001.json
- dandischema/tests/test_metadata.py
- dandischema/tests/test_models.py
This PR cleans up different elements of the schema that were a mismatch between expectations and validation mostly around the use of None.
> fix: clean up optional components of the schema

- dandischema/digests/__init__.py
- dandischema/digests/dandietag.py
- dandischema/digests/tests/test_dandietag.py
> Copy dandietag code from dandi-cli

- .github/workflows/test-dandi-cli.yml
- tools/api-with-schema.Dockerfile
> Run dandi-cli tests with dandi-api image built with local version of dandischema

- .github/workflows/test-dandi-cli.yml
ATM we really overwhelm dandischema PRs with reports from dandi-cli.
I think it will be sufficient to just test against a single python version
at least for now
> RF(CI): run dandi-cli tests only against 3.8 (but all OSes)

- dandischema/models.py
10.80507 is our test DOI site, we need to support both that and our
production site, 10.48324.
> Use a generic DOI site instead of 10.80507

- dandischema/consts.py
- dandischema/metadata.py
- dandischema/models.py
- dandischema/tests/test_models.py
This PR improves several of the items that show up in the metadata editor and elsewhere.
> improve help options

- dandischema/datacite.py
- dandischema/tests/test_datacite.py
This is only partially tested, since the data isn't actually sent off to the test server. If we were to do that in a test, we would accumulate findable and undeletable(?) DOIs.
@yarikoptic I invite followup commits with more comprehensive testing.
> Datacite publish argument

- dandischema/datacite.py
- dandischema/tests/test_datacite.py
> fixing to_datacie, allowing for None in roleName

- dandischema/consts.py
- dandischema/model_types.py
- dandischema/tests/test_models.py
this should remove NC license, which should not allow validation for any dandiset still remaining with the license. this updates the schema version as well.
> remove NC license

- dandischema/metadata.py
- dandischema/tests/test_models.py
supercedes #73 
@surchs - this PR incorporates the changes in #77 and then extends it to address the namespace issue.  i did not include explicit namespace in this PR.
- adds all properties to context
- adds test to ensure there is no conflict
> adds all properties to context with implicit dandi schema

- dandischema/exceptions.py
- dandischema/metadata.py
- dandischema/tests/test_metadata.py
I had some difficulty parsing the exceptions being thrown now that I need to differentiate between pydantic and jsonschema validation errors. This PR should mitigate that pain a bit.
Not a blocker, but nice to have in the future.
> Better exception classes

- dandischema/metadata.py
- dandischema/tests/test_metadata.py
this fixes that only dandiset.json was being used for json validation when schema version of the object did not match current schema.
> fix: associate schema key with schemas for older versions

- setup.cfg
"requests" was declared as both a normal installation requirement and as a member of the "test" extra.  This PR removes the superfluous latter declaration.
> Remove duplicate "requests" dependency

- pyproject.toml
- setup.py
This fixes a fatal problem involving a tomli version incompatibility.
This PR also removes the use of `setup_requires`, which is deprecated as of setuptools v58.3.0.
> Update versioningit version

- dandischema/models.py
- dandischema/tests/test_models.py
pydantic fixed a bug where it rightfully treats `Any` as being equivalent to `Optional`. we were abusing the previous state. This change fixes the schema to be in line with pydantic without a new schema release.
This needs to be merged before #105
> fix: address pydantic issue to make value required

- dandischema/model_types.py
- dandischema/tests/test_models.py
Add a new digest type `dandi:dandi-zarr-checksum` for representing the new zarr checksum digest.
> Add dandi:dandi-zarr-checksum digest

- dandischema/digests/tests/test_zarr.py
- dandischema/digests/zarr.py
Copy over the non-django-specific code from https://github.com/dandi/dandi-api/blob/master/dandiapi/api/zarr_checksums.py and associated tests.
There is more code in [zarr_checksums.py](https://github.com/dandi/dandi-api/blob/master/dandiapi/api/zarr_checksums.py) that deals with adding/updating/removing batches of checksums to/from the zarr archive, and also with writing the files to S3, but that didn't seem pertinent to the CLI, and it relied heavily on the Django model classes.
The CLI will need to do the legwork of walking the zarr file to feed the checksum algorithm.
> Zarr checksum calculation

- dandischema/datacite.py
- dandischema/models.py
- dandischema/tests/test_datacite.py
- adding `orcidID` to the contributors fields. It's added to `nameIdentifiers` list in `to_datacite` function. 
fixes #102
> adding Orcid ID to the contributors

- dandischema/digests/tests/test_zarr.py
- dandischema/digests/zarr.py
As we seem to be developing a consensus that empty directories are not allowed in Zarrs and should be excluded from checksum calculation, this PR makes `get_checksum()` raise a `ValueError` when both `files` and `directories` are empty.  (I was initially going to add the exception to `aggregate_checksum()`, but that messed with `EMPTY_CHECKSUM`, and I'm not sure what should happen to that, so I left it alone for now.)
> get_checksum(): Error on empty input

- dandischema/digests/dandietag.py
This change would allow `PartGenerator` to be more extensible, as if you wanted to use a different part size than 64MB, you could just do the following:
```python
class MyPartGenerator(PartGenerator):
DEFAULT_PART_SIZE = mb(500)
```
> Define `PartGenerator` default part size as class member

- dandischema/consts.py
- dandischema/models.py
- dandischema/tests/test_models.py
Ref: https://github.com/dandi/dandi-archive/issues/961
I have decided to not hardcode gui-staging. one because the fix is targetting
specifically dandisets testing, and otherwise AFAIK is not needed elsewhere.
If something wants to upload to staging, they can also adjust their CI to point
to whatever instances they upload to
@jwodder -- do you think this would work if we set env var to point to staging in testing of dandisets?
> ENH/RF: do not enforce any DANDI instance by default, support DJANGO_DANDI_WEB_APP_URL env var to specify one

- .github/workflows/test-dandi-cli.yml
This reverts commit 32fc8f66ed474b3a30dbfb3cbbe1e0290d65dc48.
Long analysis:
test_metadata2asset of dandi-cli fails integration testing started to fail regularly.
First I thought that it started to happen since #126 according to
```
(base) dandi@drogon:/mnt/backup/dandi/tinuous-logs/dandischema/2022/03$ git grep 'FAILED.*test_metadata2asset.*metadata2asset.json-metadata0' | head
24/github/pr/126/e1853d9/test-dandi-cli.yml/471-failed/3_test-dandi-cli (ubuntu-18.04, 3.8, master, normal).txt:2022-03-24T23:23:13.4506531Z FAILED tests/test_metadata.py::test_metadata2asset[metadata2asset.json-metadata0]
24/github/pr/126/e1853d9/test-dandi-cli.yml/471-failed/5_test-dandi-cli (macos-latest, 3.8, master, normal).txt:2022-03-24T23:24:11.6748940Z FAILED …
```
> Revert "Set DJANGO_DANDI_WEB_APP_URL for dandi-cli integration tests"

- setup.cfg
There is a folder in `dandischema/` that contains data files but no Python source code, and we want this folder to be included when dandischema is installed.  Currently, this folder is automatically included by the combination of `graft dandischema` in `MANIFEST.in` and `include_package_data = True` in `setup.cfg`, but because we set `packages` in `setup.cfg` to `find:` instead of `find_namespace:`, the folder itself is not recognized by setuptools as a package.  [This combination of settings is deprecated](https://github.com/pypa/setuptools/issues/3340), and the setuptools developers recommend using `find_namespace:` instead of `find:` for such situations.
> Properly include "data packages" in project

- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- dandischema/datacite.py
- dandischema/digests/dandietag.py
- dandischema/exceptions.py
- dandischema/tests/test_datacite.py
This addresses a fatal problem with an older version of black using a now-removed private part of click.
> Update pre-commit hooks and rerun

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test-dandi-cli.yml
- .github/workflows/test-nonetwork.yml
- .github/workflows/test-schema.yml
- .github/workflows/test.yml
We are currently using older versions of the updated GitHub Actions actions, and these older versions still use Node 12, [which is deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
> Update GitHub Actions action versions

- .github/workflows/test-dandi-cli.yml
- .github/workflows/test-nonetwork.yml
- .github/workflows/test.yml
The affected workflows currently use ubuntu-18.04, [which is deprecated](https://github.com/actions/runner-images/issues/6002).
> Update GitHub Actions to use ubuntu-latest

- README.md
Edit readme for stylesheet compliance/grammar/clarity/consistency.
> dandi-schema readme edit

- .pre-commit-config.yaml
Flake8 migrated to GitHub, see https://flake8.pycqa.org/en/latest/release-notes/4.0.0.html.
> Use GitHub for Flake8 pre-commit hook

- .pre-commit-config.yaml
The version of isort currently specified in `pre-commit-config.yaml` fails to install, and we might as well update the other hooks while we're at it.
> Autoupdate .pre-commit-config.yaml

- .github/workflows/test-dandi-cli.yml
Without this, one test fails due to a lack of fsspec.
> Install dandi's `extras` extra when testing

- dandischema/consts.py
0.6.3 was left out of validation schemas.
@waxlamp and @yarikoptic - when this is merged and released, the dandi-archive server should update to this version of dandi-schema
> fix: add 0.6.3 to validation

- setup.cfg
We can update the code to use pydantic 2.0 after it comes out.
See #176.
> Restrict pydantic requirement to < 2.0

- dandischema/datacite.py
- dandischema/tests/test_datacite.py
closes #168 
- added funderidtype
- added support for funders and sponsors
according to @djarecka's test the current release mints a doi for the failing metadata schema on dandiarchive, so unsure what the exact issue was. nonetheless this update should be used moving forward since people use funder/sponsor synonymously in dandiset metadata.
> added funderidtype and support for funder and sponsor roles to datacite metadata

- setup.cfg
- tox.ini
Also, add a missing type stub package.
> mypy: Set `ignore_missing_imports = False`

- dandischema/__init__.py
Because all of the items in the `__init__.py` namespace are imported from other modules, if a user of `dandischema` imports or references these items via the top-level `dandischema` module and they have mypy configured with `implicit_reexport = False`, then mypy will produce an error.  In order to fix this, we need to tell mypy that the items imported into `__init__.py` are intended for re-export via the `__all__` variable.
> Add `__all__` to `__init__.py`

- dandischema/tests/test_datacite.py
- setup.cfg
It frequently happens that a CI run fails because one instance of `test_dandimeta_datacite` on one platform got a 422 error.  The evidence suggests that this a problem on datacite's end, so this PR causes the test to simply be retried a few times until it succeeds.
> Rerun failing `test_dandimeta_datacite` tests

- pyproject.toml
`versioningit` is not meant to have an upper version bound (unless you're using custom methods, which you're not), as restricting it cuts you out of bugfixes & new features.  Also, the `{version}` field in the "format" table is now deprecated in favor of `{base_version}` (though `{version}` will continue to work).
> Unpin versioningit version

- dandischema/models.py
- dandischema/tests/test_models.py
These are unneeded now that dandischema only supports Python 3.8.
> Remove `typing_extensions` imports

- dandischema/metadata.py
Transpired by looking at never finalized
- https://github.com/dandi/dandi-schema/pull/155
as a much less intrusive and simpler approach to avoid repetitive requests for the same schema files.
> OPT: (memory) cache schema files upon first read from github

- dandischema/tests/test_datacite.py
Applying a mark to a fixture function never had any affect. It now issues a warning in Pytest V8 and will raise an error in the future version of Pytest. For details, please check out https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function.
Merging this PR is necessary for future PRs to pass the needed tests.
> Remove unneeded mark to fixture

- dandischema/consts.py
- dandischema/models.py
This PR allows the dictionary representation of `Dandiset` to have extra attributes.
ATM, packages such as [dandi-archive](https://github.com/dandi/dandi-archive) construct `Dandiset` objects using `Dandiset.model_construct()` to allow extra attributes to be passed to the resulting `Dandiset` objects. While extra attributes can be passed to the resulting `Dandiset` objects this way, the dictionary representations of these `Dandiset` objects will not contain the extra attributes unless `Dandiset` is explicitly configured to allow extra attributes. 
[dandi-archive](https://github.com/dandi/dandi-archive) requires extra attributes passed in constructing a `Dandiset` object to be present in the dictionary representation of the object. This change in this PR explicitly configures `Dandiset` to …
> Allow dictionary representation of `Dandiset` to have extra attributes

- dandischema/tests/test_models.py
Closes #223.
This fixes the reported mypy crash.  I was unable to produce an MVCE.
> Move `TempKlass`es outside of test functions

- dandischema/consts.py
- dandischema/models.py
- dandischema/tests/test_datacite.py
> Add ResourceType enum and associate with Resource model

- dandischema/models.py
- dandischema/tests/test_datacite.py
- dandischema/tests/test_metadata.py
- dandischema/tests/test_models.py
This PR provides a model level validator to ensures that a contributor acting as a contact person has an email provided per request of https://github.com/dandi/dandi-schema/issues/189.
> Add validator to ensure a contact person has email provided

- .github/workflows/test-dandi-cli.yml
- .github/workflows/test-nonetwork.yml
- .github/workflows/test.yml
The arm64  one seems to lack pythons 3.8 and 3.9. Ref: https://github.com/dandi/dandi-schema/pull/236#issuecomment-2073369726
> GitHub tests.yml CI: explicitly specify macos-12 and use python 3.11 to test against dandi-cli

- dandischema/utils.py
> Set the `$schema` key with the schema dialect

- dandischema/consts.py
- dandischema/models.py
- dandischema/tests/data/metadata/meta_000008.json
- dandischema/tests/test_datacite.py
- dandischema/tests/test_models.py
Fixes #244 
This change allows Pydantic to generate more useful validation errors by making use of [discriminated unions](https://docs.pydantic.dev/latest/concepts/unions/#discriminated-unions) where possible.
> Use discriminated unions to provide more helpful error messages

- dandischema/models.py
My guess of the intention for `BaseType.identifier` is an object either validates to an `AnyHttpUrl` or a `str` matching the pattern of `r"^[a-zA-Z0-9-]+:[a-zA-Z0-9-/\._]+$"`. If my guess is correct, the type annotation should be corrected to the proposed change in this PR.
The current type annotation of `BaseType.identifier` has problems exhibited by the `Foo.identifier` from the following example (`Baz.identifier` exhibits the solution proposed by this PR).
```py
from typing import Optional, Union
import json
from typing_extensions import Annotated
from pydantic import BaseModel, Field, AnyHttpUrl, StringConstraints, ValidationError
PATTERN = r"^[a-zA-Z0-9-]+:[a-zA-Z0-9-/\._]+$"
class Foo(BaseModel):
identifier: Optional[Union[AnyHttpUrl, str]] = Field(None, pattern=PATTERN)
class …
```
> Move pattern specification for `BaseType.identifier` to the annotation for the `str` type

- setup.cfg
Use of `typing_extensions` was reintroduced to the code in commit 0d381179 (#203), but `typing_extensions` was not added to the runtime requirements.  This PR fixes that.
> Declare `typing_extensions` dependency

- dandischema/metadata.py
- dandischema/tests/test_utils.py
- dandischema/utils.py
Closes #172 as empirically shown 
@satra do you see a quick way to add a test?
TODO
> ENH: adopt sanitize_value from dandi-cli and use for sanitization of identifier

- dandischema/metadata.py
We ran into this a week or so ago when github had their outage. This should provide a clearer exception than the `JSONDecodeError` we saw.
> Properly handle failed requests to retrieve the schema

- dandischema/metadata.py
- dandischema/models.py
- dandischema/tests/test_metadata.py
TODOs
we will need to release so that dandi-archive could take advantage of it
> Add support for detection and addition of ome/ngff "standard" into assets summary

- dandischema/datacite/__init__.py
- dandischema/datacite/tests/test_datacite.py
Some extra info on "dichotomy" of datacite json serializations could be found in
- https://github.com/dandi/dandi-schema/issues/259
and there in.  Part of this effort is RFing use of "identifiers" (removed in 4.5 serialization)
Might want to wait for addressing need to include schemas as stated in https://github.com/dandi/dandi-schema/pull/260#issuecomment-2454982938 
@djarecka  you were looking into upgrades also on Friday -- what other items were due?
> Upgrade to datacite v4.5 serialization from inveniosoftware

- dandischema/consts.py
This PR avoids multiple assignment of the constant `ALLOWED_INPUT_SCHEMAS`. Incidentally, it improves readability, and ensures `ALLOWED_VALIDATION_SCHEMAS` is always sorted.
Please, also checkout an [alternative](https://github.com/dandi/dandi-schema/pull/280/files/c44d1f3accd3c91041d39b1921a7f988d664deb4#r1938754892) to this PR posted below.
> Avoid multiple assignments of constant `ALLOWED_INPUT_SCHEMAS`

- dandischema/metadata.py
- dandischema/tests/test_metadata.py
This PR improves `migrate()` by removing bugs, making it more readable, adding argument validations, etc.  Please see commit message for more details of the improvements.
> Improve `migrate()` in `metadata.py`

- dandischema/consts.py
- dandischema/models.py
- dandischema/tests/test_metadata.py
> Remove escaping (\) of : in 2 identifiers regexes

- dandischema/consts.py
- dandischema/models.py
Fix #295 
10,000 characters is about 2-3 single-spaced pages.  Based on the OpenScope use case, the dataset descriptions (https://openscopedatafront.web.app/datasets) will fit within 10,000 characters.  See here for the context: https://github.com/dandi/dandi-archive/issues/2297.
> Increase `Description` field max character length

- .github/workflows/test-dandi-cli.yml
- .github/workflows/test-nonetwork.yml
- .github/workflows/test.yml
The `windows-2019` image is deprecated. For more details, checkout https://github.com/actions/runner-images/issues/12045
> Replace GH runner image `windows-2019` with `windows-latest`

- dandischema/conf.py
- dandischema/models.py
- dandischema/tests/test_models.py
This PR makes regex patterns restricting instance specific IDs and DOIs less strict when either or both the instance name and DOI prefix are not provided in configuring the instance config defined in `dandischema.conf`. This allows components such as dandi-cli to be instance agnostic when carrying out metadata validation.
> Relax various patterns defined in `dandischema.models` when DANDI Schema is not set to a vendor

- .github/workflows/test.yml
- dandischema/conf.py
- dandischema/datacite/__init__.py
- dandischema/datacite/tests/test_datacite.py
- dandischema/tests/test_conf.py
- dandischema/tests/test_models.py
This PR closes https://github.com/dandi/dandi-schema/issues/303.
todos:
> Make publisher info vendor specific

- dandischema/datacite/__init__.py
This PR removes unneeded import of `requests` in `dandischema.datacite`.
Note:
Please ignore the following errors in the `Type-check` workflow. They are false alarms. An [issue](https://github.com/python-jsonschema/jsonschema/issues/1382) has been filed, and the jsonschema team will resolve it.
```shell
typing: commands[0]> mypy dandischema
dandischema/utils.py:220: error: Missing positional argument "registry" in call
to "Validator"  [call-arg]
return validator_cls(schema, format_checker=validator_cls.FORM...
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...
dandischema/utils.py:223: error: Missing positional argument "registry" in call
to "Validator"  [call-arg]
return validator_cls(schema)
^~~~~~~~~~~~~~~~~~~~~
Found 2 errors in 1 file (checked 20 source files)
typing: exit 1 …
```
> Remove unneeded import of `requests` in `dandischema.datacite`

- dandischema/datacite/__init__.py
This PR handles the situation where the `instance_identifier` field of the instance config defined in `dandischema.conf` is `None` in generating the DataCite metadata.
This solution is based on a close reading of the DataCite metadata documentation at https://datacite-metadata-schema.readthedocs.io/en/4.6/properties/publisher/ which indicates that even though the `publisher` field is required in the metadata, its sub-fields, `publisherIdentifier`, `publisherIdentifierScheme`, and `schemeUri` are optional.
**Note**
Filed an [issue](https://github.com/datacite/schema-docs/issues/41) regarding DataCite Metadata Schema documentation, in part, to confirm the interpretation of the documentation which this PR is based on.
> Handle `instance_identifier` in instance config being `None` in DataCite metadata generation

- dandischema/tests/test_conf.py
Mypy at the new version of 1.18.1 complains about comparison to `unittest.mock.ANY` with object of a different type. e.g.
```console
dandischema/tests/test_conf.py:241: error: Non-overlapping equality check (left operand type: "tuple[Union[int, str], ...]", right operand type: "tuple[str, _ANY]")
[comparison-overlap]
assert exc_info.value.errors()[0]["loc"] == ("dandi_licenses", ANY)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dandischema/tests/test_conf.py:327: error: Non-overlapping equality check (left operand type: "tuple[str, int, str]", right operand type: "tuple[str, int, _ANY]")
[comparison-overlap]
assert record_tuple == ("dandischema.conf", logging.DEBUG, ANY)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dandischema/tests/test_conf.py:373: error: …
```
> Remove use of `unittest.mock.ANY` in tests to pass the stricter type checking imposed by mypy 1.18.1
